services:
  - type: web
    name: hackradar
    runtime: python
    buildCommand: pip install -r requirements.txt && cd hackradar-ui && npm install && npm run build
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false
      - key: GOOGLE_TOKEN_PICKLE
        sync: false
      - key: PORT
        value: 5000
